version: 2
jobs:
  dashing:
    docker:
      - image: autonomoustuff/docker-builds:dashing-ros-base
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-add-repository ppa:jwhitleyastuff/kvaser-linux
            apt-get update -qq
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            cd ..
            colcon build
      - run:
          name: Run Tests
          command: |
            source `find /opt/ros -maxdepth 2 -name setup.bash | sort | head -1`
            cd ..
            colcon test
            colcon test-result
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - dashing
